In [41]:
import copy
import numpy as np
import math


def distance(p1, p2):
    return math.sqrt(np.sum((p1-p2)**2))


def parse_input(filename):
    lines = open(filename, 'r').read().splitlines()

    result = []
    scanner = []

    for line in lines:
        if line.startswith("---"):
            continue
        if line == "":
            result.append(np.array(scanner))
            scanner = []
            continue

        t = line.split(",")
        scanner.append([int(t[0]), int(t[1]), int(t[2])])

    return result

def dist_map(scanner):
    result = []
    for i in range(len(scanner)):
        result.append(set([distance(scanner[i], j) for j in scanner]))
    return result
        

In [141]:
orientations = np.array([[[-1, 0, 0], [0, -1, 0], [0, 0, 1]],
                         [[-1, 0, 0], [0, 0, -1], [0, -1, 0]],
                         [[-1, 0, 0], [0, 1, 0], [0, 0, -1]],
                         [[-1, 0, 0], [0, 0, 1], [0, 1, 0]],
                         [[0, -1, 0], [-1, 0, 0], [0, 0, -1]],
                         [[0, 0, 1], [-1, 0, 0], [0, -1, 0]],
                         [[0, 1, 0], [-1, 0, 0], [0, 0, 1]],
                         [[0, 0, -1], [-1, 0, 0], [0, 1, 0]],
                         [[0, -1, 0], [0, 0, 1], [-1, 0, 0]],
                         [[0, 0, -1], [0, -1, 0], [-1, 0, 0]],
                         [[0, 1, 0], [0, 0, -1], [-1, 0, 0]],
                         [[0, 0, 1], [0, 1, 0], [-1, 0, 0]],
                         [[1, 0, 0], [0, -1, 0], [0, 0, -1]],
                         [[1, 0, 0], [0, 0, 1], [0, -1, 0]],
                         [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
                         [[1, 0, 0], [0, 0, -1], [0, 1, 0]],
                         [[0, -1, 0], [1, 0, 0], [0, 0, 1]],
                         [[0, 0, -1], [1, 0, 0], [0, -1, 0]],
                         [[0, 1, 0], [1, 0, 0], [0, 0, -1]],
                         [[0, 0, 1], [1, 0, 0], [0, 1, 0]],
                         [[0, -1, 0], [0, 0, -1], [1, 0, 0]],
                         [[0, 0, 1], [0, -1, 0], [1, 0, 0]],
                         [[0, 1, 0], [0, 0, 1], [1, 0, 0]],
                         [[0, 0, -1], [0, 1, 0], [1, 0, 0]]])

In [104]:
scanners = parse_input("../inputs/day19_test.txt")

In [93]:
def common_beacons(scanners):
    dists = [dist_map(s) for s in scanners]
    result = {}
    for i in range(len(scanners)):
        for j in range(i+1, len(scanners)):
            for b1 in range(len(scanners[i])):
                for b2 in range(len(scanners[j])):
                    if len(dists[i][b1] & dists[j][b2]) >= 12:
                        result.setdefault((i, j), set()).add((tuple(scanners[i][b1]), tuple(scanners[j][b2])))
    for k in result:
        b1 = np.array([b[0] for b in result[k]])
        b2 = np.array([b[1] for b in result[k]])
        result[k] = (b1, b2)
    return result

In [105]:
common_beacons_map = common_beacons(scanners)

In [109]:
common_beacons_map[(0,1)][0]

array([[ 404, -588, -901],
       [ 528, -643,  409],
       [ 459, -707,  401],
       [-661, -816, -575],
       [ 423, -701,  434],
       [-447, -329,  318],
       [-485, -357,  347],
       [-537, -823, -458],
       [-345, -311,  381],
       [-618, -824, -621],
       [ 390, -675, -793],
       [ 544, -627, -890]])

In [142]:
for o in orientations:
    uniq_dists = np.unique(common_beacons_map[(0,1)][1].dot(o) - common_beacons_map[(0,1)][0], axis=0)
    if len(uniq_dists) == 1:
        print(o)
        print(uniq_dists[0])

[[-1  0  0]
 [ 0  1  0]
 [ 0  0 -1]]
[ -68 1246   43]
